GSTPE-140 Web content
DavysonMelo/GSE-Frontend-Theme-Training pull request #5
Opened 2022-08-09 17:25 UTC by DavysonMelo

https://liferay.atlassian.net/browse/GSTPE-140
https://taskboard.liferay.services/#/card/GSTPE-140

2022-08-09 17:43 UTC, rennanprysthon requested changes

2022-08-09 17:43 UTC, rennanprysthon commented on modules/content-setup/ddm-templates/challenge-template.ftl
> +	<#if (Text77349973.getData())??>
Could you please rename this fieldReference name?

2022-08-22 21:24 UTC, filipemelo2002 requested changes

2022-08-22 21:24 UTC, filipemelo2002 commented on themes/stylebook-theme/src/css/custom/_challenge_web_content.scss
> +
Overall, the data is displayed as expected but for some reason, locally, the rendered web content does not look like what we have on [Figma](https://www.figma.com/file/jjwYdrZTrBS32BGWxhju65/Frontend-Training?node-id=0%3A1):
Current result:

![image](https://user-images.githubusercontent.com/26236991/186021539-1a2ee656-87a0-4d0c-b905-1523f07f98ac.png)

Expected result:

![image](https://user-images.githubusercontent.com/26236991/186021614-4dd08704-4aea-4fa5-ba7e-b6bf8921241a.png)

2022-08-23 12:39 UTC, filipemelo2002 approved these changes
just cleared the cache and redeployed. It looks good on my end. Thanks!

2022-08-23 12:51 UTC, rennanprysthon approved these changes

2022-08-23 12:51 UTC, merged